# Generated by Django 2.1.7 on 2019-02-21 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='profileimage.jpg', null=True, upload_to='photos/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', message='Enter a valid username. This value may contain only letters, numbers and [@/./+/-] characters.')], verbose_name='имя пользователя в системе'),
        ),
    ]
