# Generated by Django 2.1.7 on 2019-03-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190221_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='photos/profileimage.jpg', null=True, upload_to='photos/', verbose_name='фото'),
        ),
    ]
