# Generated by Django 2.1.7 on 2019-02-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='параграф')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='наименование секции')),
                ('section_id', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='id секции')),
                ('section_content', models.CharField(max_length=5000, verbose_name='HTML контент')),
            ],
        ),
    ]
