# Generated by Django 2.1.7 on 2019-02-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='наименование пункта меню')),
                ('menu', models.CharField(choices=[('about', 'обо мне'), ('group', 'наша группа'), ('docs', 'документы'), ('blog', 'блог'), ('contacts', 'контакты')], default='about', max_length=20, verbose_name='корневое меню')),
                ('url', models.URLField(verbose_name='гиперссылка на страницу')),
            ],
            options={
                'verbose_name': 'пункт меню',
                'verbose_name_plural': 'пункты меню',
                'db_table': 'menus',
            },
        ),
    ]
