# Generated by Django 2.1.7 on 2019-03-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190228_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='наименование секции')),
                ('enable', models.BooleanField(verbose_name='активность секции')),
            ],
            options={
                'verbose_name': 'секция',
                'verbose_name_plural': 'секции',
                'db_table': 'sections',
            },
        ),
    ]
