# Generated by Django 2.1.7 on 2019-03-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190312_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='name',
        ),
    ]
