# Generated by Django 2.1.7 on 2019-03-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190313_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(choices=[('about', 'обо мне'), ('group', 'группа'), ('news', 'новости'), ('gallery', 'фотогаллерея'), ('documents', 'документы'), ('contacts', 'контакты')], default='about', max_length=20, verbose_name='корневое меню'),
        ),
    ]
