# Generated by Django 2.1.7 on 2019-03-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190314_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(choices=[('about', 'обо мне'), ('documents', 'документы'), ('group', 'группа'), ('parents', 'для родителей'), ('methodic', 'мои разработки'), ('news', 'новости'), ('gallery', 'фотогаллерея'), ('contacts', 'контакты')], default='about', max_length=20, verbose_name='корневое меню'),
        ),
    ]
