# Generated by Django 2.1.7 on 2019-03-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20190316_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='page',
            field=models.CharField(choices=[('documents', 'Страница с документами'), ('editor', 'Страница с редактированием текста')], default='documents', max_length=20, verbose_name='тип страницы'),
        ),
    ]
