# Generated by Django 2.1.7 on 2019-03-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190317_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('subject', models.CharField(max_length=100, verbose_name='тема сообщения')),
                ('message', models.CharField(max_length=400, verbose_name='текст сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'db_table': 'feedbacks',
            },
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(choices=[('about', 'обо мне'), ('documents', 'документы'), ('group', 'группа'), ('parents', 'для родителей'), ('methodic', 'мои разработки'), ('news', 'новости'), ('gallery', 'фотогалерея'), ('contacts', 'контакты')], default='about', max_length=20, verbose_name='корневое меню'),
        ),
    ]
