# Generated by Django 2.1.7 on 2019-03-17 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20190317_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 17, 21, 41, 23, 333114, tzinfo=utc), verbose_name='время отправки'),
            preserve_default=False,
        ),
    ]
