# Generated by Django 2.1.7 on 2019-02-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование альбома(русс)')),
                ('directory', models.CharField(max_length=200, verbose_name='наименование альбома(англ')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('description', models.CharField(max_length=50, null=True, verbose_name='описание')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='время добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='последнее обновление')),
                ('photo', models.ImageField(upload_to='', verbose_name='фотография')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album', verbose_name='принадлежность к альбому')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
                'db_table': 'photos',
            },
        ),
    ]
