# Generated by Django 2.1.7 on 2019-02-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='profile',
            field=models.BooleanField(default=0, verbose_name='сделать фотографией альбома'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='directory',
            field=models.CharField(max_length=200, verbose_name='псевдоним альбома(англ)'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, verbose_name='наименование альбома(рус)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='gallery/', verbose_name='фотография'),
        ),
    ]
