# Generated by Django 2.1.7 on 2019-02-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190228_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='profile',
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album_label', to='gallery.Photo', verbose_name='Фотография профиля'),
            preserve_default=False,
        ),
    ]
