# Generated by Django 2.1.7 on 2019-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20190228_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='описание альбома(не обязательно)'),
        ),
        migrations.AlterField(
            model_name='album',
            name='directory',
            field=models.CharField(max_length=200, unique=True, verbose_name='псевдоним альбома(англ)'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='наименование альбома(рус)'),
        ),
    ]
