# Generated by Django 2.1.7 on 2019-03-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20190303_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='label',
            field=models.BooleanField(default=False, verbose_name='сделать профильной фотографией альбома'),
        ),
    ]
