# Generated by Django 2.1.7 on 2019-03-12 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Наименование документа')),
                ('description', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='описание документа')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='время добавления')),
                ('allowed', models.BooleanField(default=False, verbose_name='разрешение на публикацию')),
                ('doc', models.FileField(upload_to='documents/', verbose_name='документ')),
                ('photo', models.ImageField(blank=True, upload_to='miniatures/', verbose_name='миниатюра документа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил/автор докумнта')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
                'db_table': 'documents',
            },
        ),
    ]
