# Generated by Django 2.1.7 on 2019-03-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190313_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='photo',
            new_name='preview',
        ),
        migrations.AlterField(
            model_name='document',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Menu', verbose_name='размещение документа'),
        ),
    ]
