# Generated by Django 2.1.7 on 2019-03-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190313_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('pdf', '*.pdf файл Adobe Reader'), ('ppt', '*.ppt файл презентации MS PowerPoint 97/2003'), ('pptx', '*.pptx файл презентации MS PowerPoint'), ('doc', '*.doc текстовый файл MS Word 97/2003'), ('docx', '*.docx текстовый файл MS Word'), ('xls', '*.xls файл электронных таблиц MS Excel 97/2003'), ('xlsx', '*.xlsx файл электронных таблиц MS Excel')], default=1, max_length=4, verbose_name='тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='preview',
            field=models.ImageField(blank=True, default=None, upload_to='miniatures/', verbose_name='миниатюра документа'),
        ),
    ]
