# Generated by Django 2.1.7 on 2019-03-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190316_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('pdf', '*.pdf файл Adobe Reader'), ('ppt', '*.ppt файл презентации MS PowerPoint 97/2003'), ('pptx', '*.pptx файл презентации MS PowerPoint'), ('doc', '*.doc текстовый файл MS Word 97/2003'), ('docx', '*.docx текстовый файл MS Word'), ('xls', '*.xls файл электронных таблиц MS Excel 97/2003'), ('xlsx', '*.xlsx файл электронных таблиц MS Excel'), ('unknown', 'неизвестный тип файла')], default='pdf', max_length=7, verbose_name='тип документа'),
        ),
    ]
