# Generated by Django 2.1.7 on 2019-03-16 21:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190317_0031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0007_auto_20190316_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Наименование текста')),
                ('description', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='описание содержания')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='время добавления')),
                ('text', ckeditor.fields.RichTextField(verbose_name='редактированный текст')),
                ('allowed', models.BooleanField(default=False, verbose_name='разрешение на публикацию')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил/автор текста')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Menu', verbose_name='размещение документа')),
            ],
            options={
                'verbose_name': 'текстовая страница',
                'verbose_name_plural': 'текстовые страницы',
                'db_table': 'editors',
            },
        ),
    ]
