# Generated by Django 2.1.7 on 2019-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='header',
            field=models.FileField(null=True, upload_to='headers/', verbose_name='фотография в шапке страницы'),
        ),
        migrations.AddField(
            model_name='editor',
            name='header',
            field=models.FileField(null=True, upload_to='headers/', verbose_name='фотография в шапке страницы'),
        ),
    ]
