# Generated by Django 2.1.7 on 2019-03-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190317_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='header',
        ),
    ]
