# Generated by Django 2.1.7 on 2019-03-12 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190312_2248'),
        ('documents', '0002_auto_20190312_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Page', verbose_name='Страница для размещения документа'),
            preserve_default=False,
        ),
    ]
