# Generated by Django 2.1.7 on 2019-03-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Menu', verbose_name='Страница для размещения документа'),
        ),
    ]
