# Generated by Django 2.1.7 on 2019-02-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_id',
        ),
    ]
