# Generated by Django 2.1.7 on 2019-03-14 05:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='наименование контента')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('pic', 'Изображение'), ('VIDEO', 'Видео'), ('doc', 'Документ')], default='pic', max_length=20, verbose_name='тип контента')),
                ('file', models.ImageField(blank=True, default='content/image.jpg', null=True, upload_to='content/', verbose_name='изображение')),
                ('text', ckeditor.fields.RichTextField(verbose_name='блок текста')),
            ],
            options={
                'verbose_name': 'загружаемый контент',
                'verbose_name_plural': 'загружаемый контент',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название курса повышения квалификации')),
                ('begin_date', models.DateTimeField(verbose_name='дата начала курса')),
                ('finish_date', models.DateTimeField(verbose_name='дата завершения курса')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='длительность курса(часов)')),
                ('place', models.CharField(max_length=30, verbose_name='место проведения курса')),
            ],
            options={
                'verbose_name': 'курс повышения квалификации',
                'verbose_name_plural': 'курсы повышения квалификации',
                'db_table': 'courses',
            },
        ),
    ]
