# Generated by Django 2.1.7 on 2019-03-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20190314_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('description', models.CharField(max_length=50, null=True, verbose_name='описание')),
                ('date', models.DateField(verbose_name='дата получения')),
                ('photo', models.ImageField(upload_to='awards/', verbose_name='изображение/скан')),
            ],
            options={
                'verbose_name': 'награда',
                'verbose_name_plural': 'награды',
                'db_table': 'awards',
            },
        ),
    ]
