# Generated by Django 2.1.7 on 2019-03-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.CharField(choices=[('grateful', 'благодарность'), ('letter', 'грамота'), ('diplom', 'диплом'), ('qualification', 'удостоверение'), ('certificate', 'сертификат')], max_length=50, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Описание'),
        ),
    ]
