# Generated by Django 2.1.7 on 2019-03-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_auto_20190314_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'награждение', 'verbose_name_plural': 'награждения'},
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.CharField(choices=[('grateful', 'благодарность'), ('letter', 'грамота'), ('diplom', 'диплом'), ('qualification', 'удостоверение'), ('certificate', 'сертификат')], default=1, max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=180, verbose_name='название курса повышения квалификации'),
        ),
    ]
